POST http://localhost:8080/api/recipe/
Content-Type: application/json

{
    "id": "046b19a2-950c-4a94-83cb-d58bbe1590f7",
    "name": "Pizza Bolichera",
    "ingredients": [
        {
            "quantity": 40,
            "foodId": 2105222
        },
        {
            "quantity": 20,
            "foodId": 2105223
        }
    ]
}
