POST http://localhost:8080/api/recipe/
Content-Type: application/json

{
    "id": "64b66352-2157-44b4-bc8f-271ef01da696",
    "name": "Spagetti Bolichera",
    "ingredients": [
        {
            "quantity": 40,
            "foodId": 2105222
        },
        {
            "quantity": 20,
            "foodId": 2105223
        }
    ]
}
