PUT http://localhost:8080/api/recipe/164cd31b-00f4-4c4f-936a-18866b8bd37c/ingredient
Content-Type: application/json

{
    "ingredientId": "cc098058-4540-4efc-bfa9-595aee31a4b0",
    "quantity": 20,
    "foodId": 12131
}
