PUT http://localhost:8080/api/recipe/046b19a2-950c-4a94-83cb-d58bbe1590f7/ingredient
Content-Type: application/json

{
    "ingredientId": "1594d144-648b-4933-8a18-adb86bc9d293",
    "quantity": 60,
    "foodId": 12131
}
